using LexiconLang.Language;

namespace LexiconLang.Fantasy;

public static class FantasyMeanings
{
    public static readonly MeaningPack Industrial = new(
        "fantasy.industrial",
        "1.0.0",
        new Meaning[]
        {
            new("rune", WordClass.Noun, new[] { "magic", "power" }, "rune"),
            new("oath", WordClass.Noun, new[] { "contract", "honor" }, "oath"),
            new("anvil", WordClass.Noun, new[] { "industry", "craft" }, "anvil"),
            new("hex", WordClass.Noun, new[] { "magic", "curse" }, "hex"),
            new("beast", WordClass.Noun, new[] { "animal", "war" }, "beast"),
            new("forge", WordClass.Verb, new[] { "industry", "creation" }, "forge"),
            new("vow", WordClass.Noun, new[] { "contract", "honor" }, "vow"),
            new("crown", WordClass.Noun, new[] { "power", "rule" }, "crown"),
            new("scepter", WordClass.Noun, new[] { "power", "rule" }, "scepter"),
            new("throne", WordClass.Noun, new[] { "power", "rule" }, "throne"),
            new("citadel", WordClass.Noun, new[] { "structure", "power" }, "citadel"),
            new("fortress", WordClass.Noun, new[] { "structure", "strength" }, "fortress"),
            new("dungeon", WordClass.Noun, new[] { "structure", "dark" }, "dungeon"),
            new("crypt", WordClass.Noun, new[] { "structure", "death" }, "crypt"),
            new("tower", WordClass.Noun, new[] { "structure", "height" }, "tower"),
            new("grove", WordClass.Noun, new[] { "nature", "magic" }, "grove"),
            new("ruin", WordClass.Noun, new[] { "structure", "old" }, "ruin"),
            new("potion", WordClass.Noun, new[] { "magic", "craft" }, "potion"),
            new("spell", WordClass.Noun, new[] { "magic", "power" }, "spell"),
            new("curse", WordClass.Noun, new[] { "magic", "evil" }, "curse"),
            new("bless", WordClass.Verb, new[] { "magic", "good" }, "bless"),
            new("witch", WordClass.Noun, new[] { "magic", "person" }, "witch"),
            new("sorcerer", WordClass.Noun, new[] { "magic", "person" }, "sorcerer"),
            new("priestess", WordClass.Noun, new[] { "divine", "person" }, "priestess"),
            new("priest", WordClass.Noun, new[] { "divine", "person" }, "priest"),
            new("knight", WordClass.Noun, new[] { "war", "honor" }, "knight"),
            new("squire", WordClass.Noun, new[] { "war", "youth" }, "squire"),
            new("merchant", WordClass.Noun, new[] { "society", "trade" }, "merchant"),
            new("peasant", WordClass.Noun, new[] { "society" }, "peasant"),
            new("guard", WordClass.Noun, new[] { "war", "protection" }, "guard"),
            new("archer", WordClass.Noun, new[] { "war", "skill" }, "archer"),
            new("warrior", WordClass.Noun, new[] { "war", "strength" }, "warrior"),
            new("champion", WordClass.Noun, new[] { "war", "honor" }, "champion"),
            new("elf", WordClass.Noun, new[] { "race", "nature" }, "elf"),
            new("dwarf", WordClass.Noun, new[] { "race", "earth" }, "dwarf"),
            new("human", WordClass.Noun, new[] { "race" }, "human"),
            new("orc", WordClass.Noun, new[] { "race", "war" }, "orc"),
            new("halfling", WordClass.Noun, new[] { "race", "small" }, "halfling"),
            new("dragon", WordClass.Noun, new[] { "race", "power" }, "dragon"),
            new("goblin", WordClass.Noun, new[] { "race", "evil" }, "goblin"),
            new("troll", WordClass.Noun, new[] { "race", "strength" }, "troll"),
            new("necromancer", WordClass.Noun, new[] { "magic", "death", "evil" }, "necromancer"),
            new("basilisk", WordClass.Noun, new[] { "beast", "poison" }, "basilisk"),
            new("phoenix", WordClass.Noun, new[] { "beast", "fire" }, "phoenix"),
            new("griffon", WordClass.Noun, new[] { "beast", "sky" }, "griffon"),
            new("unicorn", WordClass.Noun, new[] { "beast", "magic" }, "unicorn"),
            new("mage", WordClass.Noun, new[] { "magic", "power" }, "mage"),
            new("sage", WordClass.Noun, new[] { "knowledge", "old" }, "sage"),
            new("oracle", WordClass.Noun, new[] { "magic", "knowledge" }, "oracle"),
            new("sigil", WordClass.Noun, new[] { "magic", "symbol" }, "sigil"),
            new("amulet", WordClass.Noun, new[] { "magic", "protection" }, "amulet"),
            new("talisman", WordClass.Noun, new[] { "magic", "luck" }, "talisman"),
            new("staff", WordClass.Noun, new[] { "magic", "item" }, "staff"),
            new("wand", WordClass.Noun, new[] { "magic", "item" }, "wand"),
            new("chalice", WordClass.Noun, new[] { "magic", "item" }, "chalice"),
            new("tome", WordClass.Noun, new[] { "knowledge", "item" }, "tome"),
            new("scroll", WordClass.Noun, new[] { "knowledge", "item" }, "scroll"),
            new("grimoire", WordClass.Noun, new[] { "magic", "item" }, "grimoire"),
            new("cursed", WordClass.Adjective, new[] { "magic", "evil" }, "cursed"),
            new("blessed", WordClass.Adjective, new[] { "magic", "good" }, "blessed"),
            new("enchanted", WordClass.Adjective, new[] { "magic" }, "enchanted"),
            new("mystical", WordClass.Adjective, new[] { "magic" }, "mystical"),
            new("ethereal", WordClass.Adjective, new[] { "magic" }, "ethereal"),
            new("undead", WordClass.Adjective, new[] { "death" }, "undead"),
            new("immortal", WordClass.Adjective, new[] { "attribute" }, "immortal"),
            new("legendary", WordClass.Adjective, new[] { "attribute" }, "legendary"),
            new("noble", WordClass.Adjective, new[] { "attribute" }, "noble"),
            new("valiant", WordClass.Adjective, new[] { "attribute" }, "valiant"),
            new("sinister", WordClass.Adjective, new[] { "evil" }, "sinister"),
            new("infernal", WordClass.Adjective, new[] { "evil" }, "infernal"),
            new("celestial", WordClass.Adjective, new[] { "divine" }, "celestial"),
            new("divine", WordClass.Adjective, new[] { "holy" }, "divine"),
            new("demonic", WordClass.Adjective, new[] { "evil" }, "demonic"),
            new("spectral", WordClass.Adjective, new[] { "death" }, "spectral"),
            new("phantom", WordClass.Noun, new[] { "death" }, "phantom"),
            new("spirit", WordClass.Noun, new[] { "soul" }, "spirit"),
            new("ghost", WordClass.Noun, new[] { "death" }, "ghost"),
            new("wraith", WordClass.Noun, new[] { "death" }, "wraith"),
            new("spectre", WordClass.Noun, new[] { "death" }, "spectre"),
            new("lich", WordClass.Noun, new[] { "death", "magic" }, "lich"),
            new("vampire", WordClass.Noun, new[] { "death" }, "vampire"),
            new("werewolf", WordClass.Noun, new[] { "beast" }, "werewolf"),
            new("summon", WordClass.Verb, new[] { "magic" }, "summon"),
            new("create", WordClass.Verb, new[] { "creation" }, "create"),
            new("craft", WordClass.Verb, new[] { "industry" }, "craft"),
            new("construct", WordClass.Verb, new[] { "industry" }, "construct"),
        });
}
